recipe: wordpress
config:
  php: '8.1'
  webroot: wordpress
services:
  appserver:
    xdebug: true
    config:
      php: .config/php.ini
events:
  pre-init:
    - appserver: /app/.scripts/check-php-ini.sh
  post-rebuild:
    - appserver: /app/.scripts/setup-db.sh