name: wp-autoloader
recipe: wordpress
proxy:
  mail:
    - mail.wp-autoloader.lndo.site
config:
  php: '8.1'
  webroot: wordpress
services:
  appserver:
    xdebug: true
    config:
      php: .config/php.ini
  mail:
    type: mailhog
    hogfrom:
      - appserver